/**
 * Root layout for the Next.js application.
 * Provides global styles, fonts, and essential providers such as Material UI theming and caching.
 */
import type { Metadata } from "next";  // Importing Metadata type for defining page metadata
import { Roboto } from "next/font/google";  // Importing the Roboto font from Google Fonts via Next.js
import "./globals.css";  // Importing global CSS for styling across the application
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';  // Importing MUI AppRouterCacheProvider for caching in Next.js app router
import { ThemeProvider } from "@mui/material";  // Importing ThemeProvider from Material UI for theming
import theme from "../theme";  // Importing the custom theme configuration
import { JSX, ReactNode } from "react";  // Importing ReactNode type for typing children props
import { AuthProvider } from "@/context/AuthContext";

/**
 * Metadata for the entire application.
 * This object defines the HTML metadata such as title and description.
 * 
 * @type {Metadata}
 */
export const metadata: Metadata = {
  title: "Create Next App",  // Title of the app
  description: "Generated by create next app",  // Description for the app, used in SEO
};

/**
 * Configure and load the Roboto font.
 * 
 * @constant
 * @type {{ className: string, style: object, variable: string }}
 * @property {string} className - The generated CSS class name for the font.
 * @property {object} style - Additional inline styles for the font.
 * @property {string} variable - CSS variable name for the font.
 */
const roboto: { className: string; style: object; variable: string } = Roboto({
  weight: ['300', '400', '500', '700'],  // Font weights to load
  subsets: ['latin'],  // Subsets of the font (character sets)
  display: 'swap',  // Ensures text is displayed with fallback until the font is loaded
  variable: '--font-roboto',  // Custom CSS variable name for the font
});


/**
 * Root layout component that wraps the entire application.
 * Provides global configuration, theming, and caching.
 * 
 * @function RootLayout
 * @param {Object} props - Component properties.
 * @param {ReactNode} props.children - The children components to be rendered inside the layout.
 * @returns {JSX.Element} - The root layout structure.
 */
export default function RootLayout({
  navbar,
  children,  // React children passed to the layout (pages and components)
}: Readonly<{
  navbar: ReactNode;
  children: ReactNode;  // Type enforcement to ensure children are valid React nodes
}>): JSX.Element {
  return (
    <html lang="en">  {/* Set the language attribute for accessibility and SEO */}
      <body className={roboto.variable}>  {/* Apply the Roboto font variable as a class to the body */}
        <AppRouterCacheProvider>  {/* Enables caching for Material UI in Next.js App Router */}
          <AuthProvider>
            <ThemeProvider theme={theme}>  {/* Provides the custom Material UI theme to the entire app */}
              {navbar}
              {children}  {/* Render the child components (pages and app content) */}
            </ThemeProvider>
          </AuthProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
